kind: Secret
apiVersion: v1
metadata:
  name: tavily-search-key
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  tavily-search-api-key: Z2hwXzE4ZmhaeDRnQ214YjBTdHE3RzM1Wk9lMHdGTXhGVzNOVUJuawo=
type: Opaque
