apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../mcp-servers/openshift-mcp
  # - ../mcp-servers/slack-mcp
  - ../notebooks
  - deployment.yaml
  - pvc.yaml
  - route.yaml
  - service.yaml
  - ../streamlit-client
  # - otel-collector-sidecar.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: run-config
    files:
      - config.yaml=run.yaml
